/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as MailRouteImport } from './routes/mail'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as FsReviewsRouteImport } from './routes/fs-reviews'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FleetIndexRouteImport } from './routes/fleet/index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as ReviewIdRouteImport } from './routes/review.$id'
import { Route as IssuesIdRouteImport } from './routes/issues.$id'
import { Route as FsReviewsIdRouteImport } from './routes/fs-reviews.$id'
import { Route as AgentAgentIdRouteImport } from './routes/agent.$agentId'

const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const MailRoute = MailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const FsReviewsRoute = FsReviewsRouteImport.update({
  id: '/fs-reviews',
  path: '/fs-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReviewRoute,
} as any)
const IssuesIdRoute = IssuesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IssuesRoute,
} as any)
const FsReviewsIdRoute = FsReviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FsReviewsRoute,
} as any)
const AgentAgentIdRoute = AgentAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/board': typeof BoardRoute
  '/events': typeof EventsRoute
  '/fs-reviews': typeof FsReviewsRouteWithChildren
  '/issues': typeof IssuesRouteWithChildren
  '/mail': typeof MailRoute
  '/nodes': typeof NodesRoute
  '/review': typeof ReviewRouteWithChildren
  '/sessions': typeof SessionsRoute
  '/squad': typeof SquadRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/fs-reviews/$id': typeof FsReviewsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/agent/': typeof AgentIndexRoute
  '/fleet': typeof FleetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/events': typeof EventsRoute
  '/fs-reviews': typeof FsReviewsRouteWithChildren
  '/issues': typeof IssuesRouteWithChildren
  '/mail': typeof MailRoute
  '/nodes': typeof NodesRoute
  '/review': typeof ReviewRouteWithChildren
  '/sessions': typeof SessionsRoute
  '/squad': typeof SquadRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/fs-reviews/$id': typeof FsReviewsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/agent': typeof AgentIndexRoute
  '/fleet': typeof FleetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/board': typeof BoardRoute
  '/events': typeof EventsRoute
  '/fs-reviews': typeof FsReviewsRouteWithChildren
  '/issues': typeof IssuesRouteWithChildren
  '/mail': typeof MailRoute
  '/nodes': typeof NodesRoute
  '/review': typeof ReviewRouteWithChildren
  '/sessions': typeof SessionsRoute
  '/squad': typeof SquadRoute
  '/agent/$agentId': typeof AgentAgentIdRoute
  '/fs-reviews/$id': typeof FsReviewsIdRoute
  '/issues/$id': typeof IssuesIdRoute
  '/review/$id': typeof ReviewIdRoute
  '/agent/': typeof AgentIndexRoute
  '/fleet/': typeof FleetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/board'
    | '/events'
    | '/fs-reviews'
    | '/issues'
    | '/mail'
    | '/nodes'
    | '/review'
    | '/sessions'
    | '/squad'
    | '/agent/$agentId'
    | '/fs-reviews/$id'
    | '/issues/$id'
    | '/review/$id'
    | '/agent/'
    | '/fleet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/events'
    | '/fs-reviews'
    | '/issues'
    | '/mail'
    | '/nodes'
    | '/review'
    | '/sessions'
    | '/squad'
    | '/agent/$agentId'
    | '/fs-reviews/$id'
    | '/issues/$id'
    | '/review/$id'
    | '/agent'
    | '/fleet'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/board'
    | '/events'
    | '/fs-reviews'
    | '/issues'
    | '/mail'
    | '/nodes'
    | '/review'
    | '/sessions'
    | '/squad'
    | '/agent/$agentId'
    | '/fs-reviews/$id'
    | '/issues/$id'
    | '/review/$id'
    | '/agent/'
    | '/fleet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRouteWithChildren
  BoardRoute: typeof BoardRoute
  EventsRoute: typeof EventsRoute
  FsReviewsRoute: typeof FsReviewsRouteWithChildren
  IssuesRoute: typeof IssuesRouteWithChildren
  MailRoute: typeof MailRoute
  NodesRoute: typeof NodesRoute
  ReviewRoute: typeof ReviewRouteWithChildren
  SessionsRoute: typeof SessionsRoute
  SquadRoute: typeof SquadRoute
  FleetIndexRoute: typeof FleetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail': {
      id: '/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof MailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fs-reviews': {
      id: '/fs-reviews'
      path: '/fs-reviews'
      fullPath: '/fs-reviews'
      preLoaderRoute: typeof FsReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/issues/$id': {
      id: '/issues/$id'
      path: '/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof IssuesIdRouteImport
      parentRoute: typeof IssuesRoute
    }
    '/fs-reviews/$id': {
      id: '/fs-reviews/$id'
      path: '/$id'
      fullPath: '/fs-reviews/$id'
      preLoaderRoute: typeof FsReviewsIdRouteImport
      parentRoute: typeof FsReviewsRoute
    }
    '/agent/$agentId': {
      id: '/agent/$agentId'
      path: '/$agentId'
      fullPath: '/agent/$agentId'
      preLoaderRoute: typeof AgentAgentIdRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface AgentRouteChildren {
  AgentAgentIdRoute: typeof AgentAgentIdRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentAgentIdRoute: AgentAgentIdRoute,
  AgentIndexRoute: AgentIndexRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface FsReviewsRouteChildren {
  FsReviewsIdRoute: typeof FsReviewsIdRoute
}

const FsReviewsRouteChildren: FsReviewsRouteChildren = {
  FsReviewsIdRoute: FsReviewsIdRoute,
}

const FsReviewsRouteWithChildren = FsReviewsRoute._addFileChildren(
  FsReviewsRouteChildren,
)

interface IssuesRouteChildren {
  IssuesIdRoute: typeof IssuesIdRoute
}

const IssuesRouteChildren: IssuesRouteChildren = {
  IssuesIdRoute: IssuesIdRoute,
}

const IssuesRouteWithChildren =
  IssuesRoute._addFileChildren(IssuesRouteChildren)

interface ReviewRouteChildren {
  ReviewIdRoute: typeof ReviewIdRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewIdRoute: ReviewIdRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRouteWithChildren,
  BoardRoute: BoardRoute,
  EventsRoute: EventsRoute,
  FsReviewsRoute: FsReviewsRouteWithChildren,
  IssuesRoute: IssuesRouteWithChildren,
  MailRoute: MailRoute,
  NodesRoute: NodesRoute,
  ReviewRoute: ReviewRouteWithChildren,
  SessionsRoute: SessionsRoute,
  SquadRoute: SquadRoute,
  FleetIndexRoute: FleetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
